# Generated by Django 4.2.30 on 2026-04-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(choices=[('BM', 'Banco Metropolitano'), ('BC', 'BANDEC'), ('BP', 'BPA')], max_length=5)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entity', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciliation.bank')),
            ],
            options={
                'verbose_name': 'Transacción Bancaria',
                'verbose_name_plural': 'Transacciones Bancarias',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('matched', 'Conciliada'), ('reviewed', 'Revisada'), ('flagged', 'Marcada'), ('resolved', 'Resuelta')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_logs', to='reconciliation.banktransaction')),
            ],
            options={
                'verbose_name': 'Log de Conciliación',
                'verbose_name_plural': 'Logs de Conciliación',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date'], name='reconciliat_transac_e125e8_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status'], name='reconciliat_status_f58082_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank'], name='reconciliat_bank_id_3ec6da_idx'),
        ),
    ]
