# Generated by Django 4.2.30 on 2026-04-26 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('reconciliation', '0002_alter_bank_id_alter_banktransaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('overdraft_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('entry_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='bank_accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_reference', models.CharField(max_length=255)),
                ('original_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_type', models.CharField(max_length=50)),
                ('bank_fee', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_transactions', to='bank_accounts.bankaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reconciliation.bankstatement')),
            ],
            options={
                'verbose_name': 'Bank Statement Transaction',
                'verbose_name_plural': 'Bank Statement Transactions',
                'ordering': ['-bank_statement__statement_date', 'current_reference'],
            },
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='reconciliationlog',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='ReconciliationLog',
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['current_reference'], name='reconciliat_current_a8e0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['bank_statement'], name='reconciliat_bank_st_0eb3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['date'], name='reconciliat_date_ce94e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['statement_date'], name='reconciliat_stateme_d5d38d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account'], name='reconciliat_bank_ac_8536bd_idx'),
        ),
    ]
