# Generated by Django 4.2.30 on 2026-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_bankstatement_file_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('bank_account', 'statement_date'), name='unique_bank_statement_bank_date'),
        ),
    ]
