# Generated by Django 4.2.30 on 2026-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0005_bankstatement_unique_bank_statement_bank_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='operation_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='operation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
