# Generated by Django 4.2.30 on 2026-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0006_bankstatementtransaction_operation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reconciled', 'Conciliado')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['status'], name='reconciliat_status_153cf6_idx'),
        ),
    ]
