# Generated by Django 4.2.30 on 2026-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0007_bankstatementtransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementtransaction',
            name='operation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
