# Generated by Django 6.0.4 on 2026-04-23 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('overdraft_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('reserved_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('entry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='bank_accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Extracto Bancario',
                'verbose_name_plural': 'Extractos Bancarios',
                'db_table': 'bank_statements',
                'ordering': ['-statement_date', 'bank_account'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_reference', models.CharField(db_index=True, max_length=100)),
                ('original_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(db_index=True, help_text='Código de oficina para decodificación', max_length=50)),
                ('entry_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], max_length=20)),
                ('bank_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(choices=[('CUP', 'Peso Cubano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso Mexicano')], default='CUP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_transactions', to='bank_accounts.bankaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='statements.bankstatement')),
            ],
            options={
                'verbose_name': 'Transacción de Extracto',
                'verbose_name_plural': 'Transacciones de Extractos',
                'db_table': 'bank_statement_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['statement_date'], name='bank_statem_stateme_700ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['period_start'], name='bank_statem_period__69d61b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['period_end'], name='bank_statem_period__a3eced_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account'], name='bank_statem_bank_ac_380d05_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['current_reference'], name='bank_statem_current_dc34e4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['office_code'], name='bank_statem_office__79de09_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['entry_type'], name='bank_statem_entry_t_ca98a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['bank_statement'], name='bank_statem_bank_st_06154c_idx'),
        ),
    ]
