# Generated by Django 4.2.30 on 2026-05-05 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='users_usera_user_id_63b4df_idx',
            old_name='users_user__user_id_50b4a8_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='users_usera_action_acb2ad_idx',
            old_name='users_user__action_7d4f9e_idx',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
