# Generated by Django 4.2.30 on 2026-05-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('error', 'Error'), ('estados_cuenta', 'Estados de cuenta'), ('conciliacion', 'Conciliación'), ('transacciones', 'Transacciones'), ('exportacion', 'Exportación'), ('informes', 'Informes'), ('notificaciones', 'Notificaciones'), ('otro', 'Otro')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Solucionado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bug Report',
                'verbose_name_plural': 'Bug Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='users_bugre_type_32ab35_idx'), models.Index(fields=['status'], name='users_bugre_status_193b5e_idx'), models.Index(fields=['reporter', '-created_at'], name='users_bugre_reporte_4611dc_idx')],
            },
        ),
    ]
