# Generated by Django 4.2.30 on 2026-05-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(default='#1E88E5', max_length=7),
        ),
    ]
