# Generated by Django 4.2.30 on 2026-05-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='type',
            field=models.CharField(choices=[('error', 'Error'), ('estados_cuenta', 'Estados de cuenta'), ('conciliacion', 'Conciliación'), ('transacciones', 'Transacciones'), ('exportacion', 'Exportación'), ('informes', 'Informes'), ('notificaciones', 'Notificaciones'), ('usuario', 'Usuario'), ('contrasena', 'Contraseña'), ('otro', 'Otro')], max_length=30),
        ),
    ]
