# Generated by Django 6.0.4 on 2026-04-23 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Códigos',
                'verbose_name_plural': 'Catálogos de Códigos',
                'db_table': 'code_catalog',
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['category'], name='code_catalo_categor_18e365_idx'), models.Index(fields=['code'], name='code_catalo_code_865a81_idx')],
            },
        ),
    ]
