# Generated by Django 6.0.4 on 2026-04-25 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('overdraft_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('entry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='bank_accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta Bancario',
                'verbose_name_plural': 'Estados de Cuenta Bancarios',
                'db_table': 'bank_statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_reference', models.CharField(max_length=100)),
                ('original_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('office_code', models.CharField(db_index=True, max_length=50)),
                ('entry_type', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], max_length=20)),
                ('bank_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='CUP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_transactions', to='bank_accounts.bankaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.bankstatement')),
            ],
            options={
                'verbose_name': 'Transacción de Estado de Cuenta',
                'verbose_name_plural': 'Transacciones de Estados de Cuenta',
                'db_table': 'bank_statement_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['bank_account', 'statement_date'], name='bank_statem_bank_ac_ad6ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['period_start', 'period_end'], name='bank_statem_period__512471_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['bank_statement'], name='bank_statem_bank_st_06154c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['office_code'], name='bank_statem_office__79de09_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementtransaction',
            index=models.Index(fields=['current_reference'], name='bank_statem_current_dc34e4_idx'),
        ),
    ]
