# Generated by Django 4.2.30 on 2026-04-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_fix_accountstate_schema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountState',
        ),
    ]
