# Generated by Django 4.2.30 on 2026-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_delete_accountstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
